### PR TITLE
created spotify_api.py

### PR DESCRIPTION
**Pull request by Jon-117**
search_spotify_playlists() returns a list of 10 Playlist objects.

added playlist class to help with transferring data to weathermoods. Little different than the Playlist class in PR #11. Added pretty_string method for easy display to user.

@hm2247fg @Riley-Strandlund 
please review. Riley, with this and the classes PR you should be good to go on db

### CODE REVIEW

**Comment by Riley-Strandlund** [comment]
When I try to run the code I get your error 'failed to retrieve the access token'. I don't know why it's failing to retrieve the token. Does it work when you do it?

**Comment by Jon-117** [comment]
> When I try to run the code I get your error 'failed to retrieve the access token'. I don't know why it's failing to retrieve the token. Does it work when you do it?

@Riley-Strandlund 
Yes. You'll want to take the Client ID and Client Secret I shared in the Slack Channel to be able to access. I saved them as environment variables on my pc with names SPOTIFY_WEB_DEV_WEATHERMOOD_SECRET and SPOTIFY_WEB_DEV_WEATHERMOOD_ID

@hm2247fg FYI You'll want to do this too

@claraj - is there an easy way to share the Environment Variables inside the repo without sacrificing security or do you have a suggested method for how to handle this?

**Review by Riley-Strandlund — APPROVED** [review]
Tested it and it works.

**Review by Riley-Strandlund — APPROVED** [review]
I resolved the conflicts by replacing the old playlist class with the new one from the spotify_api branch.

**Pull request merged**
